version: '3'
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ./server/config.yaml:/config.yaml
    entrypoint: ./server
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
    entrypoint: /client
    environment:
      - CLI_ID=1
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
    entrypoint: /client
    environment:
      - CLI_ID=2
    networks:
      - testing_net
    depends_on:
      - server    

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24